@startuml
!define RECTANGLE class

actor "Administrador" as Admin

rectangle "Sistema de Gestão de Eletrodomésticos" {
    rectangle "Frontend - React" {
        Admin -> "Frontend - React" : "Preenche dados da marca"
    }

    rectangle "Backend - Django" {
        "Frontend - React" -> "Backend - Django" : "Envia dados da marca via API"
    }

    rectangle "Banco de Dados - PostgreSQL" {
        "Backend - Django" -> "Banco de Dados - PostgreSQL" : "Armazenar dados da marca"
    }
}
@enduml
