@startuml
!define RECTANGLE class

actor "Administrador" as Admin
actor "Banco de Dados" as DB

rectangle "Sistema de Gestão de Eletrodomésticos" {
    Admin -> "Sistema de Gestão de Eletrodomésticos" : "Atualizar preço do eletrodoméstico"
    "Sistema de Gestão de Eletrodomésticos" -> DB : "Atualizar preço no banco de dados"
}
@enduml
