@startuml
!define RECTANGLE class

actor "Administrador" as Admin

rectangle "Sistema de Gestão de Eletrodomésticos" {
    rectangle "Frontend - React" {
        Admin -> "Frontend - React" : "Atualiza preço do eletrodoméstico"
    }

    rectangle "Backend - Django" {
        "Frontend - React" -> "Backend - Django" : "Envia novo preço via API"
    }

    rectangle "Banco de Dados - PostgreSQL" {
        "Backend - Django" -> "Banco de Dados - PostgreSQL" : "Atualizar preço no banco de dados"
    }
}
@enduml
