version: '3.8'

services:
  db:
    container_name: postgres-db-dev
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: eletro
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eletrodomesticos-api
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:5432", "--", "node", "dist/server.js"]
    networks:
      - app-network


volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
