@startuml
!define RECTANGLE class

actor "Administrador" as Admin

rectangle "Sistema de Gestão de Eletrodomésticos" {
    rectangle "Frontend - React" {
        Admin -> "Frontend - React" : "Solicita histórico de preços"
    }

    rectangle "Backend - Django" {
        "Backend - Django" -> "Banco de Dados - PostgreSQL" : "Consulta histórico de preços"
        "Backend - Django" -> "Frontend - React" : "Retorna histórico de preços"
    }
}
@enduml
