@startuml
!define RECTANGLE class

actor "Administrador" as Admin
actor "Banco de Dados" as DB

rectangle "Sistema de Gestão de Eletrodomésticos" {
    Admin -> "Sistema de Gestão de Eletrodomésticos" : "Registrar nova marca"
    "Sistema de Gestão de Eletrodomésticos" -> DB : "Armazenar dados da marca"
}
@enduml