name: Docker Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker image
        run: |
          docker build \
            -f eletrodomesticos-api/Dockerfile \
            -t eletrodomesticos-api-test \
            ./eletrodomesticos-api

      - name: Verify that dist/server.js exists in image
        run: |
          docker run --rm eletrodomesticos-api-test \
            node -e "require('fs').existsSync('./dist/server.js') || process.exit(1)"

